/**
 * Beard / facial-hair overlays on the head canvas, which may extend below
 * the chin (rows 16+ fall onto the chest). b base, B highlight, v dark,
 * R ribbon, m mouth shown through the beard.
 */
export const BEARD_STYLES = {
  none: { down: [], left: [], up: [] },
  stubble: {
    down: [
      ...Array(11).fill(''),
      '..v..........v..',
      '..vv.v.v..v.vv..',
      '...vvv....vvv...',
      '....vvv.vvvv....',
      '.....vvvvvv.....',
    ],
    left: [
      ...Array(11).fill(''),
      '..........vv....',
      '..v.v.v.vvv.....',
      '..mmvv.vvvv.....',
      '...vvvvvvv......',
      '....vvvvvv......',
    ],
    up: [],
  },
  mustache: {
    down: [
      ...Array(12).fill(''),
      '....vbBBBBbv....',
      '...vb.mmm..bv...',
    ],
    left: [
      ...Array(12).fill(''),
      'bBBbbv..........',
      '.mmv............',
    ],
    up: [],
  },
  full: {
    down: [
      ...Array(10).fill(''),
      '..b..........b..',
      '..bb........bb..',
      '..bbbbBBBBbbbb..',
      '..bbbb.mm.bbbb..',
      '...bbbbbbbbbb...',
      '....vbbbbbbv....',
      '.....vvbbvv.....',
      '.......vv.......',
    ],
    left: [
      ...Array(10).fill(''),
      '..........bb....',
      '.........bbb....',
      'bBBbbbbbbbbb....',
      '.mmbbbbbbbbv....',
      '.bbbbbbbbbv.....',
      '..vbbbbbbv......',
      '...vvbbvv.......',
    ],
    up: [
      ...Array(10).fill(''),
      '.b............b.',
      '.b............b.',
    ],
  },
  great: {
    // The captain's famous beard: huge, black, braided with red ribbons.
    down: [
      ...Array(9).fill(''),
      '..b..........b..',
      '..bb........bb..',
      '.bbbb......bbbb.',
      '.bbbbbBBBBbbbbb.',
      '.bbbbb.mm.bbbbb.',
      'bbbbbbbbbbbbbbbb',
      'bbbBbbbbbbbbBbbb',
      '.bbbbbbBBbbbbbb.',
      '.vbbbbbbbbbbbbv.',
      '..vbbbbvvbbbbv..',
      '...vbbv..vbbv...',
      '...vRRv..vRRv...',
      '....bb....bb....',
      '....bv....bv....',
      '....vv....vv....',
    ],
    left: [
      ...Array(9).fill(''),
      '..........bb....',
      '.........bbb....',
      '........bbbb....',
      'bBBBbbbbbbbb....',
      '.mmbbbbbbbbbv...',
      'bbbbbbbbbbbbv...',
      'bbbBbbbbbbbv....',
      '.bbbbbbbbbbv....',
      '.vbbbbbbbbv.....',
      '..vbbbbbbv......',
      '...vbbbbv.......',
      '...vRRRv........',
      '....bbv.........',
      '....bv..........',
      '....vv..........',
    ],
    up: [
      ...Array(10).fill(''),
      '.b............b.',
      'bb............bb',
      'bb............bb',
      '.b............b.',
    ],
  },
  goatee: {
    down: [
      ...Array(12).fill(''),
      '.....vbBBbv.....',
      '......mmm.......',
      '......vbbv......',
      '.......vv.......',
    ],
    left: [
      ...Array(12).fill(''),
      'bBBv............',
      '.mm.............',
      '.bbv............',
      '..vv............',
    ],
    up: [],
  },
  sideburns: {
    down: [
      ...Array(8).fill(''),
      '..v..........v..',
      '..bv........vb..',
      '..bv........vb..',
      '..bb........bb..',
      '..vb........bv..',
    ],
    left: [
      ...Array(8).fill(''),
      '..........bv....',
      '.........vbb....',
      '.........bbb....',
      '.........bbv....',
    ],
    up: [
      ...Array(8).fill(''),
      '.v............v.',
      '.b............b.',
      '.b............b.',
    ],
  },
};
