/**
 * Hair overlays on the 16x16 head canvas: h base, H highlight, j dark.
 * Rows not listed are empty. Each style has down/left/up variants.
 */
export const HAIR_STYLES = {
  bald: { down: [], left: [], up: [] },
  short: {
    down: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHhhhj...',
      '..jhHHHHhhhhhj..',
      '..jhHhhhhhhhhj..',
      '..jhhhjjjjhhhj..',
      '..jh........hj..',
    ],
    left: [
      '................',
      '................',
      '.....jjjjjjj....',
      '...jjhHHHhhhj...',
      '..jhHHHhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhjjjhhhhhhj..',
      '...........hhj..',
      '...........hj...',
    ],
    up: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHHhhj...',
      '..jhhHHHHhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jjhhhhhhhhjj..',
      '...jjhhhhhhjj...',
      '.....jjjjjj.....',
    ],
  },
  long: {
    down: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHhhhj...',
      '..jhHHHHhhhhhj..',
      '.jhHHhhhhhhhhhj.',
      '.jhhhjjjjjjhhhj.',
      '.jhh........hhj.',
      '.jhh........hhj.',
      '.jh..........hj.',
      '.jh..........hj.',
      '.jh..........hj.',
      '.jj..........jj.',
    ],
    left: [
      '................',
      '................',
      '.....jjjjjjj....',
      '...jjhHHHhhhj...',
      '..jhHHHhhhhhhj..',
      '..jhhhhhhhhhhhj.',
      '..jhjjjhhhhhhhj.',
      '..........hhhhj.',
      '..........hhhhj.',
      '..........hhhhj.',
      '...........hhhj.',
      '...........hhhj.',
      '............hjj.',
    ],
    up: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHHhhj...',
      '..jhhHHHHhhhhj..',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jjhhhhhhhhhhjj.',
      '..jjjhhhhhhjjj..',
    ],
  },
  ponytail: {
    down: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHhhhj...',
      '..jhHHHhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhjjjjjjhhj..',
      '..jh........hj..',
    ],
    left: [
      '................',
      '................',
      '.....jjjjjjj....',
      '...jjhHHHhhhj...',
      '..jhHHHhhhhhhjj.',
      '..jhhhhhhhhhhjhj',
      '..jhjjjhhhhhhjhj',
      '...........hhjhj',
      '...........hj.hj',
      '..............hj',
      '..............jj',
    ],
    up: [
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhHHHHhhj...',
      '..jhhHHHHhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhjjhhhhj..',
      '..jhhhjhhjhhhj..',
      '..jjhhhjjhhhjj..',
      '...jjhhhhhhjj...',
      '.....jjhhjj.....',
      '.......hh.......',
      '.......hh.......',
      '.......jj.......',
    ],
  },
  bun: {
    down: [
      '......jjjj......',
      '.....jhHHhj.....',
      '....jjhhhhjj....',
      '...jhhHHHhhhj...',
      '..jhHHHHhhhhhj..',
      '..jhHhhhhhhhhj..',
      '..jhhhjjjjhhhj..',
      '..jh........hj..',
    ],
    left: [
      '..........jjj...',
      '.........jhHhj..',
      '.....jjjjjhhhj..',
      '...jjhHHHhjjj...',
      '..jhHHHhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhjjjhhhhhhj..',
      '...........hhj..',
    ],
    up: [
      '......jjjj......',
      '.....jhHHhj.....',
      '....jjhhhhjj....',
      '...jhhHHHHhhj...',
      '..jhhHHHHhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jjhhhhhhhhjj..',
      '...jjhhhhhhjj...',
      '.....jjjjjj.....',
    ],
  },
  wild: {
    down: [
      '................',
      '..j..j.jj.j..j..',
      '.jhjjhjhhjhjjhj.',
      '.jhHHhhHHhhHhhj.',
      'jhHHHhhhhhhhhhhj',
      'jhhhhhhhhhhhhhhj',
      'jhhjjjjjjjjjjhhj',
      'jhh..........hhj',
      '.jh..........hj.',
      '.jj..........jj.',
    ],
    left: [
      '................',
      '...j.jj.j..j....',
      '..jhjhhjhjjhj...',
      '..jhHHhhHHhhhj..',
      '.jhHHHhhhhhhhhj.',
      '.jhhhhhhhhhhhhhj',
      '.jhjjjhhhhhhhhhj',
      '..........hhhhhj',
      '..........hhhhj.',
      '...........hhj..',
    ],
    up: [
      '................',
      '..j..j.jj.j..j..',
      '.jhjjhjhhjhjjhj.',
      '.jhhhhhHHhhhhhj.',
      'jhhhhHHHHhhhhhhj',
      'jhhhhhhhhhhhhhhj',
      'jhhhhhhhhhhhhhhj',
      'jhhhhhhhhhhhhhhj',
      'jhhhhhhhhhhhhhhj',
      '.jhhhhhhhhhhhhj.',
      '.jjhhhhhhhhhhjj.',
      '..jjjhhhhhhjjj..',
    ],
  },
  curly: {
    down: [
      '................',
      '....jj.jj.jj....',
      '...jhhjhhjhhj...',
      '..jhHHhHHhhhhj..',
      '.jhHHhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhjhjjjjhjhhj.',
      '.jhj........jhj.',
      '..j..........j..',
    ],
    left: [
      '................',
      '.....jj.jj.jj...',
      '....jhhjhhjhhj..',
      '...jhHHhHHhhhhj.',
      '..jhHHhhhhhhhhj.',
      '..jhhhhhhhhhhhhj',
      '..jhjjjhhhhhhhhj',
      '..........hhhhhj',
      '..........jhhhj.',
      '...........jjj..',
    ],
    up: [
      '................',
      '....jj.jj.jj....',
      '...jhhjhhjhhj...',
      '..jhhhhHHhhhhj..',
      '.jhhhhHHHhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jhhhhhhhhhhhhj.',
      '.jjhhhhhhhhhhjj.',
      '..jjhhhhhhhhjj..',
      '...jjjhhhhjjj...',
    ],
  },
  cropped: {
    down: [
      '................',
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhhhhhhhj...',
      '..jhhhhhhhhhhj..',
      '..jh........hj..',
    ],
    left: [
      '................',
      '................',
      '................',
      '.....jjjjjjj....',
      '....jhhhhhhhj...',
      '...jhhhhhhhhhj..',
      '...........hhj..',
    ],
    up: [
      '................',
      '................',
      '................',
      '....jjjjjjjj....',
      '...jhhhhhhhhj...',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '..jhhhhhhhhhhj..',
      '...jhhhhhhhhj...',
    ],
  },
};
