/**
 * Hat overlays on the 16x16 head canvas: a base, A light, q dark,
 * T trim, t trim dark, s spots/pattern.
 */
export const HAT_STYLES = {
  none: { down: [], left: [], up: [] },
  tricorn: {
    down: [
      '................',
      '......qqqq......',
      '....qaaAAaaq....',
      '...qaAAAAAaaq...',
      'T..qaaaaaaaaq..T',
      'TTTaaaaaaaaaaTTT',
      '.tTTaaaaaaaaTTt.',
      '..ttTTTaaTTTtt..',
      '.....ttTTtt.....',
    ],
    left: [
      '................',
      '......qqqq......',
      '....qaaAAaq.....',
      '...qaAAAAaaq....',
      '..TqaaaaaaaaqT..',
      'TTTaaaaaaaaaaaTT',
      '.tTTTaaaaaaTTTt.',
      '...ttTTTTTTtt...',
    ],
    up: [
      '................',
      '......qqqq......',
      '....qaaaaaaq....',
      '...qaaAAaaaaq...',
      'T..qaaaaaaaaq..T',
      'TTTaaaaaaaaaaTTT',
      '.tTTTaaaaaaTTTt.',
      '...tttTTTTttt...',
    ],
  },
  bandana: {
    down: [
      '................',
      '................',
      '................',
      '....qaaaaaaq....',
      '...aAAsAaaaaq...',
      '..aAAAaaasaaaq..',
      '..aasaaaaaaaaq..',
      '..qqqqqqqqqqqq..',
    ],
    left: [
      '................',
      '................',
      '................',
      '.....qaaaaaq....',
      '....aAAAsaaaq...',
      '...aAsAaaaaaaq..',
      '..aaaaaaasaaaqaa',
      '..qqqqqqqqqqqa.a',
      '..............a.',
    ],
    up: [
      '................',
      '................',
      '................',
      '....qaaaaaaq....',
      '...aaaAsAaaaq...',
      '..aaaAAAaasaaq..',
      '..aasaaaaaaaaq..',
      '..qqqqqaaqqqqq..',
      '......aqqa......',
      '.....aa..aa.....',
    ],
  },
  kerchief: {
    down: [
      '................',
      '................',
      '.....qaaaaq.....',
      '...qaaAAAaaq....',
      '..qaAAAAaaaaq...',
      '..aAAaaaaaaaaq..',
      '.qaaaaaaaaaaaaq.',
      '.qqqqqqqqqqqqqq.',
      '.q............q.',
    ],
    left: [
      '................',
      '................',
      '......qaaaaq....',
      '....qaaAAAaaq...',
      '...qaAAAAaaaaq..',
      '...aAAaaaaaaaaq.',
      '..qaaaaaaaaaaaaq',
      '..qqqqqqqqqqqqaa',
      '.............aqa',
      '..............a.',
    ],
    up: [
      '................',
      '................',
      '.....qaaaaq.....',
      '...qaaaaaaaaq...',
      '..qaaAAAAaaaaq..',
      '..aaAAAAaaaaaq..',
      '.qaaaaaaaaaaaaq.',
      '.qaaaaaaaaaaaaq.',
      '.qqqqqqaaqqqqqq.',
      '......aqqa......',
      '.....aqa.aqa....',
      '.....aa...aa....',
    ],
  },
  knitcap: {
    down: [
      '................',
      '......qaaq......',
      '....qaaAAaaq....',
      '...qaAAAAaaaq...',
      '..qaAAaaaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    left: [
      '................',
      '.......qaq......',
      '.....qaAAaq.....',
      '...qaAAAAaaq....',
      '..qaAAaaaaaaq...',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    up: [
      '................',
      '......qaaq......',
      '....qaaaaaaq....',
      '...qaaAAaaaaq...',
      '..qaaAAAaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
  },
  tophat: {
    down: [
      '.....qqqqqq.....',
      '....qaAAaaaq....',
      '....qaAaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '..qqaaaaaaaaqq..',
      '..qqqqqqqqqqqq..',
    ],
    left: [
      '.....qqqqqq.....',
      '....qaAAaaaq....',
      '....qaAaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '.qqaaaaaaaaaaqq.',
      '.qqqqqqqqqqqqqq.',
    ],
    up: [
      '.....qqqqqq.....',
      '....qaaaaaaq....',
      '....qaaaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '..qqaaaaaaaaqq..',
      '..qqqqqqqqqqqq..',
    ],
  },
};
