/**
 * Hat overlays on the 16x16 head canvas: a base, A light, q dark,
 * T trim, t trim dark, s spots/pattern.
 */
export const HAT_STYLES = {
  none: { down: [], left: [], up: [] },
  tricorn: {
    down: [
      '................',
      '......qqqq......',
      '....qaaAAaaq....',
      '...qaAAAAAaaq...',
      'T..qaaaaaaaaq..T',
      'TTTaaaaaaaaaaTTT',
      '.tTTaaaaaaaaTTt.',
      '..ttTTTaaTTTtt..',
      '.....ttTTtt.....',
    ],
    left: [
      '................',
      '......qqqq......',
      '....qaaAAaq.....',
      '...qaAAAAaaq....',
      '..TqaaaaaaaaqT..',
      'TTTaaaaaaaaaaaTT',
      '.tTTTaaaaaaTTTt.',
      '...ttTTTTTTtt...',
    ],
    up: [
      '................',
      '......qqqq......',
      '....qaaaaaaq....',
      '...qaaAAaaaaq...',
      'T..qaaaaaaaaq..T',
      'TTTaaaaaaaaaaTTT',
      '.tTTTaaaaaaTTTt.',
      '...tttTTTTttt...',
    ],
  },
  bandana: {
    down: [
      '................',
      '................',
      '................',
      '....qaaaaaaq....',
      '...aAAsAaaaaq...',
      '..aAAAaaasaaaq..',
      '..aasaaaaaaaaq..',
      '..qqqqqqqqqqqq..',
    ],
    left: [
      '................',
      '................',
      '................',
      '.....qaaaaaq....',
      '....aAAAsaaaq...',
      '...aAsAaaaaaaq..',
      '..aaaaaaasaaaqaa',
      '..qqqqqqqqqqqa.a',
      '..............a.',
    ],
    up: [
      '................',
      '................',
      '................',
      '....qaaaaaaq....',
      '...aaaAsAaaaq...',
      '..aaaAAAaasaaq..',
      '..aasaaaaaaaaq..',
      '..qqqqqaaqqqqq..',
      '......aqqa......',
      '.....aa..aa.....',
    ],
  },
  kerchief: {
    down: [
      '................',
      '................',
      '.....qaaaaq.....',
      '...qaaAAAaaq....',
      '..qaAAAAaaaaq...',
      '..aAAaaaaaaaaq..',
      '.qaaaaaaaaaaaaq.',
      '.qqqqqqqqqqqqqq.',
      '.q............q.',
    ],
    left: [
      '................',
      '................',
      '......qaaaaq....',
      '....qaaAAAaaq...',
      '...qaAAAAaaaaq..',
      '...aAAaaaaaaaaq.',
      '..qaaaaaaaaaaaaq',
      '..qqqqqqqqqqqqaa',
      '.............aqa',
      '..............a.',
    ],
    up: [
      '................',
      '................',
      '.....qaaaaq.....',
      '...qaaaaaaaaq...',
      '..qaaAAAAaaaaq..',
      '..aaAAAAaaaaaq..',
      '.qaaaaaaaaaaaaq.',
      '.qaaaaaaaaaaaaq.',
      '.qqqqqqaaqqqqqq.',
      '......aqqa......',
      '.....aqa.aqa....',
      '.....aa...aa....',
    ],
  },
  knitcap: {
    down: [
      '................',
      '......qaaq......',
      '....qaaAAaaq....',
      '...qaAAAAaaaq...',
      '..qaAAaaaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    left: [
      '................',
      '.......qaq......',
      '.....qaAAaq.....',
      '...qaAAAAaaq....',
      '..qaAAaaaaaaq...',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    up: [
      '................',
      '......qaaq......',
      '....qaaaaaaq....',
      '...qaaAAaaaaq...',
      '..qaaAAAaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
  },
  // Story Phase 4: Pete's nightcap (he works the night watch), a striped
  // stocking cap with a bobble drooping over one ear.
  nightcap: {
    down: [
      '................',
      '.......qaaq.....',
      '.....qaAAaaq.sT.',
      '....qaAAAaaaqsT.',
      '...qaAAaaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    left: [
      '................',
      '.......qaq......',
      '.....qaAAaq.....',
      '...qaAAAAaaq.sT.',
      '..qaAAaaaaaaqsT.',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
    up: [
      '................',
      '......qaaq......',
      '....qaaaaaaq..sT',
      '...qaaAAaaaaq.sT',
      '..qaaAAAaaaaaq..',
      '..qaaaaaaaaaaq..',
      '..TtTtTtTtTtTt..',
      '..tTtTtTtTtTtT..',
    ],
  },
  // A galley cooking pot worn as a hat, handle sticking out: the Grand
  // Stenchmaster's crown of office.
  pot: {
    down: [
      '................',
      '.....qqqqqq.....',
      '....qaAAaaaqTTT.',
      '....qaAaaaaq..T.',
      '...qaaaaaaaaq...',
      '..TTTTTTTTTTTT..',
      '..tqqqqqqqqqqt..',
    ],
    left: [
      '................',
      '.....qqqqqq.....',
      '....qaAAaaaqTTT.',
      '....qaAaaaaq..T.',
      '...qaaaaaaaaq...',
      '..TTTTTTTTTTTT..',
      '..tqqqqqqqqqqt..',
    ],
    up: [
      '................',
      '.....qqqqqq.....',
      '.TTTqaaaaaaq....',
      '.T..qaaaaaaq....',
      '...qaaaaaaaaq...',
      '..TTTTTTTTTTTT..',
      '..tqqqqqqqqqqt..',
    ],
  },
  // Story Phase 5: the Grand Stenchmaster's ceremonial hat. A tall, crooked
  // burgundy crown with a band of that green, a cream badge, and a limp
  // green puff on top that is meant to be a stink-cloud.
  stenchhat: {
    down: [
      '......TTqqqq....',
      '.....TttaAAaq...',
      '......qaAsAaq...',
      '.....qaaaaaaq...',
      '.....qTTTTTTq...',
      '...qqaaaaaaaaqq.',
      '...qqqqqqqqqqqq.',
    ],
    left: [
      '.......TTqqq....',
      '......TttAAaq...',
      '.....qaAsAaaq...',
      '.....qaaaaaaq...',
      '.....qTTTTTTq...',
      '..qqaaaaaaaaaaq.',
      '..qqqqqqqqqqqqq.',
    ],
    up: [
      '......TTqqqq....',
      '.....TttaaaAq...',
      '......qaaaaaq...',
      '.....qaaaaaaq...',
      '.....qTTTTTTq...',
      '...qqaaaaaaaaqq.',
      '...qqqqqqqqqqqq.',
    ],
  },
  tophat: {
    down: [
      '.....qqqqqq.....',
      '....qaAAaaaq....',
      '....qaAaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '..qqaaaaaaaaqq..',
      '..qqqqqqqqqqqq..',
    ],
    left: [
      '.....qqqqqq.....',
      '....qaAAaaaq....',
      '....qaAaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '.qqaaaaaaaaaaqq.',
      '.qqqqqqqqqqqqqq.',
    ],
    up: [
      '.....qqqqqq.....',
      '....qaaaaaaq....',
      '....qaaaaaaq....',
      '....qaaaaaaq....',
      '....qTTTTTTq....',
      '..qqaaaaaaaaqq..',
      '..qqqqqqqqqqqq..',
    ],
  },
};
