/**
 * Head templates (16x16 canvas) per facing. Letters are palette roles:
 *   s/S/d/D skin base/highlight/shade/deep   e pupil   E eye white
 *   m mouth   b brow (hair colour)   n nose shade
 * The chin is on row 15; eyes on rows 9-10.
 * "right" is generated by mirroring "left".
 */
export const HEAD = {
  down: [
    '................',
    '................',
    '................',
    '................',
    '.....ssssss.....',
    '...sSSSSssssd...',
    '..sSSSSSsssssd..',
    '..sSSSsssssssd..',
    '..sSsbbsssbbsd..',
    '.dsSsEessseEsdd.',
    '.dsSsEessseEsdd.',
    '..sSssssnssssd..',
    '..sssssnnsssdd..',
    '...ssssmmmsdd...',
    '....sssssddd....',
    '.....dddddd.....',
  ],
  left: [
    '................',
    '................',
    '................',
    '................',
    '......sssss.....',
    '....sSSSssssd...',
    '...sSSSsssssdd..',
    '..sSSsssssssdd..',
    '..sbbsssssssdd..',
    '.sEesssssdsdd...',
    '.sEesssssdSdd...',
    'ssssssssssdd....',
    '.nsssssssssd....',
    '..mmsssssddd....',
    '...ssssssdd.....',
    '....dddddd......',
  ],
  up: [
    '................',
    '................',
    '................',
    '................',
    '.....ssssss.....',
    '...sssssssssd...',
    '..sssssssssssd..',
    '..sssssssssssd..',
    '..sssssssssssd..',
    '.dssssssssssddd.',
    '.dssssssssssddd.',
    '..sssssssssssd..',
    '..ssssssssssdd..',
    '...sssssssssd...',
    '....sssssssd....',
    '.....dddddd.....',
  ],
};

/** Mouth / eye variants for field expressions (applied over the down/left head). */
export const FACE_VARIANTS = {
  // Asleep: eyes shut (lids drawn as a dark line), for sleepers lying in hammocks and bedrolls.
  asleep: {
    down: { rows: { 9: '.dsSsssssssssdd.', 10: '.dsSseessseesdd.' } },
    left: { rows: { 9: '.ssssssssdsdd...', 10: '.seesssssdSdd...' } },
  },
  surprised: {
    down: { rows: { 13: '...ssssmmsdd....', 12: '..ssssmmmmsddd..' } },
    left: { rows: { 13: '..mmsssssddd....', 12: '.nmmsssssssd....' } },
  },
};
