import { PixelCanvas } from '../PixelCanvas.js';
import { PAL } from '../palette.js';

/**
 * 16x16 item icons. Item data refers to these by name ("icon": "tonic").
 * Adding an icon = adding an entry here; content validation checks names.
 */
const O = PAL.black;

export const ICONS = {
  hardtack: {
    rows: [
      '................',
      '................',
      '..oooooooooooo..',
      '.oYYYYYYYYYYYyo.',
      '.oYyyyyyyyyyyro.',
      '.oYydyyydyyydro.',
      '.oYyyyyyyyyyyro.',
      '.oYyyyyyyyyyyro.',
      '.oYydyyydyyydro.',
      '.oYyyyyyyyyyyro.',
      '.oYyyyyyyyyyyro.',
      '.oYydyyydyyydro.',
      '.oyrrrrrrrrrrro.',
      '..oooooooooooo..',
      '................',
      '................',
    ],
    colors: { o: O, Y: PAL.rope4, y: PAL.rope3, r: PAL.rope2, d: PAL.rope1 },
  },
  tonic: {
    rows: [
      '................',
      '.....oooooo.....',
      '.....oCccCo.....',
      '......oCCo......',
      '......ogGo......',
      '.....ogGGGo.....',
      '....ogRRRRRo....',
      '...ogRrRRRRRo...',
      '...oRrwRRRRRo...',
      '...oRrRRRRRdo...',
      '...oRRRRRRRdo...',
      '...oRRRRRRddo...',
      '....odRRRddo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
    colors: { o: O, C: PAL.lea4, c: PAL.lea3, g: '#d8f0f8', G: '#88b8c8', R: PAL.red3, r: PAL.red4, w: '#ffffff', d: PAL.red2 },
  },
  rum: {
    rows: [
      '................',
      '.......oo.......',
      '......oCCo......',
      '......oBBo......',
      '......oBbo......',
      '.....oBBbbo.....',
      '....oBBBbbbo....',
      '....oBwBbbbo....',
      '....oLLLLLLo....',
      '....oLlXXlLo....',
      '....oLLLLLLo....',
      '....oBBBbbbo....',
      '....oBBbbbbo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
    colors: { o: O, C: PAL.lea4, B: '#4a5626', b: '#2c3616', w: '#b8c890', L: PAL.cloth3, l: PAL.cloth2, X: PAL.red2 },
  },
  bandage: {
    rows: [
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '....oWWWWWWo....',
      '...oWWwwwwWWo...',
      '...oWwoooowWo...',
      '...oWwo..owWo...',
      '...oWwoooowWo...',
      '...oWWwwwwWWo...',
      '....oWWWWWWooo..',
      '.....oooooowWWo.',
      '..........oWWwo.',
      '...........oooo.',
      '................',
      '................',
    ],
    colors: { o: O, W: PAL.cloth4, w: PAL.cloth2 },
  },
  rusty_key: {
    rows: [
      '................',
      '................',
      '..oooo..........',
      '.oRRRRo.........',
      'oRr..rRo........',
      'oR....Ro........',
      'oRr..rRoooooooo.',
      '.oRRRRRRRRRRRRRo',
      '..oooooooorRoRRo',
      '..........oRooRo',
      '...........o..o.',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    colors: { o: O, R: '#a05a2c', r: '#6a3818' },
  },
  treasure_key: {
    rows: [
      '................',
      '..ooooo.........',
      '.oGgGgGo........',
      'oGg...gGo.......',
      'oG.....Go.......',
      'oGg...gGoooooooo',
      '.oGgGgGGGGGGGGGo',
      '..oooooooodGodGo',
      '.........oGGoGGo',
      '..........oo.oo.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    colors: { o: O, G: PAL.gold3, g: PAL.gold4, d: PAL.gold1 },
  },
  fuse: {
    rows: [
      '................',
      '............y...',
      '..........yYy...',
      '...........F....',
      '..........oF....',
      '.....ooooofo....',
      '...ooCCCCCo.....',
      '..oCCccccCCo....',
      '.oCcoooooocCo...',
      '.oCcoCCCCocCo...',
      '.oCcocccCocCo...',
      '.oCCooooocCCo...',
      '..oCCccccCCo....',
      '...ooCCCCoo.....',
      '.....oooo.......',
      '................',
    ],
    colors: { o: O, C: PAL.iron3, c: PAL.iron2, y: PAL.fire3, Y: PAL.fire4, F: PAL.fire1, f: PAL.rope2 },
  },
  cutlass: {
    rows: [
      '................',
      '.............oo.',
      '............oWo.',
      '...........oWso.',
      '..........oWso..',
      '.........oWso...',
      '........oWso....',
      '.......oWso.....',
      '..oo..oWso......',
      '..oGooWso.......',
      '...oGGso........',
      '...ooGGo........',
      '..oLooGGo.......',
      '.oLLo.oGo.......',
      '.oLo...o........',
      '..o.............',
    ],
    colors: { o: O, W: PAL.iron5, s: PAL.iron3, G: PAL.gold3, L: PAL.lea3 },
  },
  axe: {
    rows: [
      '................',
      '........ooo.....',
      '.......oWWso....',
      '......oWWsso....',
      '.....oWWssoo....',
      '....oWWssoLo....',
      '....ooooooLo....',
      '.........oLo....',
      '........oLo.....',
      '.......oLo......',
      '......oLo.......',
      '.....oLo........',
      '....oLo.........',
      '...oLo..........',
      '...oo...........',
      '................',
    ],
    colors: { o: O, W: PAL.iron5, s: PAL.iron3, L: PAL.wood3 },
  },
  coat: {
    rows: [
      '................',
      '....oo....oo....',
      '...oRRoooooRRo..',
      '..oRRRrwwrRRRo..',
      '..oRRRrwwrRRRo..',
      '.oRRRrrwwrrRRRo.',
      '.oRRoRrwwrRoRRo.',
      '.oRRoRRGGRRoRRo.',
      '.oGGoRRooRRoGGo.',
      '.oRRoRRRRRRoRRo.',
      '..ooRRRGGRRRoo..',
      '....oRRRRRRo....',
      '....oRRrrRRo....',
      '....oRRooRRo....',
      '....ooo..ooo....',
      '................',
    ],
    colors: { o: O, R: PAL.red2, r: PAL.red1, w: PAL.cloth4, G: PAL.gold3 },
  },
  boots: {
    rows: [
      '................',
      '..oooo..........',
      '..oBBo..........',
      '..oBbo..........',
      '..oBbo..oooo....',
      '..oBbo..oBBo....',
      '..oBbo..oBbo....',
      '..oBbo..oBbo....',
      '..oBbboooBbo....',
      '..oBbbbBoBbo....',
      '..ooooooBBbbo...',
      '........oBbbbbo.',
      '........ooooooo.',
      '................',
      '................',
      '................',
    ],
    colors: { o: O, B: PAL.lea3, b: PAL.lea2 },
  },
  doubloon: {
    rows: [
      '................',
      '................',
      '.....oooooo.....',
      '....oGGGGGGo....',
      '...oGgggggGGo...',
      '..oGgGGooGGgGo..',
      '..oGgGoWWoGgGo..',
      '..oGgGoWWoGgGo..',
      '..oGgGGooGGgGo..',
      '..oGgGoGGoGgGo..',
      '..oGGgGGGGgGdo..',
      '...oGGgggggdo...',
      '....oddddddo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
    colors: { o: O, G: PAL.gold3, g: PAL.gold4, d: PAL.gold1, W: PAL.white },
  },
  charm: {
    rows: [
      '................',
      '..oo........oo..',
      '...oo......oo...',
      '....oo....oo....',
      '.....oo..oo.....',
      '......oooo......',
      '.....oWooWo.....',
      '....oWWooWWo....',
      '....oWWooWWo....',
      '.....oWooWo.....',
      '.....oWooWo.....',
      '......oo.oo.....',
      '................',
      '................',
      '................',
      '................',
    ],
    colors: { o: PAL.lea1, W: PAL.cloth4 },
  },
  fishbone: {
    rows: [
      '................',
      '................',
      '................',
      '..o..o..o..o....',
      '...o..o..o..o.oo',
      '.oWWWWWWWWWWWoWo',
      '...o..o..o..o.oo',
      '..o..o..o..o....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    colors: { o: PAL.cloth1, W: PAL.cloth4 },
  },
  gold: {
    rows: [
      '................',
      '................',
      '................',
      '.......oooooo...',
      '......oGggggGo..',
      '......oddddddo..',
      '...ooooooooooo..',
      '..oGgggggGo.....',
      '..odddddddo.....',
      '..oGgggggGoooo..',
      '..oddddddoGggGo.',
      '..oGgggggGoddddo',
      '..oddddddoGgggGo',
      '...oooooooodddo.',
      '..........oooo..',
      '................',
    ],
    colors: { o: O, G: PAL.gold3, g: PAL.gold4, d: PAL.gold1 },
  },
  ledger: {
    rows: [
      '................',
      '...oooooooooo...',
      '..oLLLLLLLLLLo..',
      '..oLppppppppLo..',
      '..oLpkkkkkkpLo..',
      '..oLppppppppLo..',
      '..oLpkkkkkpLLo..',
      '..oLppppppppLo..',
      '..oLpkkkkkkpLo..',
      '..oLppppppppLo..',
      '..oLLLLLLLLLLo..',
      '..oLLLLGGLLLLo..',
      '...oooooooooo...',
      '................',
      '................',
      '................',
    ],
    colors: { o: O, L: PAL.green2, p: PAL.cloth4, k: PAL.cloth1, G: PAL.gold3 },
  },
  shirt: {
    rows: [
      '................',
      '................',
      '...oooo..oooo...',
      '..oWWWWooWWWWo..',
      '.oWWWWWwwWWWWWo.',
      '.oWWoWWWWWWoWWo.',
      '.ooooWWWWWWoooo.',
      '....oWWWWWWo....',
      '....oWWWWWWo....',
      '....oWWWWWWo....',
      '....oWwwwwWo....',
      '....oooooooo....',
      '................',
      '................',
      '................',
      '................',
    ],
    colors: { o: O, W: PAL.cloth3, w: PAL.cloth2 },
  },
};

export function buildItemIcons() {
  const out = {};
  for (const [name, def] of Object.entries(ICONS)) {
    out[`icon_${name}`] = new PixelCanvas(16, 16).stamp(def.rows, 0, 0, def.colors);
  }
  return out;
}

export const ICON_NAMES = Object.keys(ICONS);
